# Generated by Django 4.2.18 on 2025-03-13 14:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_default_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, default='IE', max_length=2, null=True),
        ),
    ]
