# Generated by Django 4.2.18 on 2025-03-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash on Pickup')], default='card', max_length=10),
        ),
    ]
