# Generated by Django 4.2.18 on 2025-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Alter the county field in the Order model.
    """

    dependencies = [
        ('checkout', '0007_alter_order_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(
                choices=[
                    ('Carlow', 'Carlow'),
                    ('Cavan', 'Cavan'),
                    ('Clare', 'Clare'),
                    ('Cork', 'Cork'),
                    ('Donegal', 'Donegal'),
                    ('Dublin', 'Dublin'),
                    ('Galway', 'Galway'),
                    ('Kerry', 'Kerry'),
                    ('Kildare', 'Kildare'),
                    ('Kilkenny', 'Kilkenny'),
                    ('Laois', 'Laois'),
                    ('Leitrim', 'Leitrim'),
                    ('Limerick', 'Limerick'),
                    ('Longford', 'Longford'),
                    ('Louth', 'Louth'),
                    ('Mayo', 'Mayo'),
                    ('Meath', 'Meath'),
                    ('Monaghan', 'Monaghan'),
                    ('Offaly', 'Offaly'),
                    ('Roscommon', 'Roscommon'),
                    ('Sligo', 'Sligo'),
                    ('Tipperary', 'Tipperary'),
                    ('Waterford', 'Waterford'),
                    ('Westmeath', 'Westmeath'),
                    ('Wexford', 'Wexford'),
                    ('Wicklow', 'Wicklow'),
                ],
                max_length=80,
                null=True,
                blank=True,
            ),
        ),
    ]
