# Generated by Django 4.2.18 on 2025-03-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_privacypolicy_alter_baker_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Allergen Information', max_length=200)),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allergen Information',
                'verbose_name_plural': 'Allergen Information',
            },
        ),
    ]
