# Generated by Django 4.2.18 on 2025-03-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='serving_size',
            field=models.CharField(default='Serving Size', max_length=50),
        ),
    ]
