# Generated by Django 4.2.18 on 2025-03-28 22:12

from django.db import migrations


def add_allergens(apps, schema_editor):
    Allergen = apps.get_model('products', 'Allergen')
    allergens = [
        "Milk", "Eggs", "Peanuts", "Tree Nuts", "Soybeans", "Wheat",
        "Fish", "Crustaceans", "Mollusks", "Sesame Seeds",
        "Celery", "Mustard", "Lupin", "Sulphur Dioxide (Sulphites)",
        "Corn", "Coconut", "Pine Nuts", "Legumes",
        "Bananas", "Avocado", "Kiwi", "Cocoa", "Honey", "Gluten",
        "Traces of milk", "Traces of eggs", "Traces of nuts",
        "Traces of alcohol", "Gluten"
    ]
    for allergen in allergens:
        Allergen.objects.get_or_create(name=allergen)


class Migration(migrations.Migration):

    dependencies = [
        ('products',
         '0003_allergen_remove_product_allergens_product_allergens'),
    ]

    operations = [
        migrations.RunPython(add_allergens),
    ]
